.mode columns
.headers on
.nullvalue NULL


SELECT T.IDPLAYER AS "ID", T.NAME AS "Name", T.BIRTHDATE AS "Birthdate", COUNT(*) AS "TOTAL GOALS" FROM(


SELECT * FROM PLAYER L JOIN PERSON E ON E.IDPERSON = L.IDPLAYER JOIN EVENT E ON E.IDPLAYER = L.IDPLAYER JOIN GOAL G ON G.IDGOAL = E.IDEVENT where self = 0

) T GROUP BY T.IDPLAYER order by COUNT(*) desc;