.mode columns
.headers on
.nullvalue NULL



SELECT C.IDCLUB AS "ID", C.NAME AS "Name", C.YEAR AS "Year", C."group" AS "Group", S.NAME AS "Stadium", O.NAME AS "Country", P.NAME AS "Coach"

FROM

CLUB C JOIN COUNTRY O ON C.IDCOUNTRY = O.IDCOUNTRY
JOIN STADIUM S ON S.IDSTADIUM = C.IDSTADIUM
JOIN COACH A ON A.IDCOACH = C.IDCOACH
JOIN PERSON P ON P.IDPERSON = A.IDCOACH WHERE O.NAME = "Portugal";